<script type="text/javascript" src="tools/jquery.js"></script>
<script type="text/javascript" src="tools/bootstrap.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js"></script>
<script type="text/javascript" src="tools/underscore-min.js"></script>
<script type="text/javascript" src="tools/tooltipster.min.js"></script>
<script type="text/javascript" src="tools/date-en-AU.js"></script>
<script type="text/javascript" src="tools/time.js"></script>
<script type="text/javascript" src="tools/moment.js"></script>
<script type="text/javascript" src="tools/checklist-model.js"></script>